/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import connect_to_database.KoneksiDatabase;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Luh Putu Monica Arysta Putri Suastawan - 2005551090  
 * @author Gede Rico Wijaya - 2005551091
 */

public class FormMendataBarang extends javax.swing.JFrame {

    /**
     * Creates new form FormMendataBarang
     */
    public FormMendataBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NamaBarang_Field = new javax.swing.JTextField();
        Kategori_ComboBox = new javax.swing.JComboBox<>();
        SatuanBarang_Field = new javax.swing.JTextField();
        TambahBarang_Label = new javax.swing.JLabel();
        Kembali_Label = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        NamaBarang_Field.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        NamaBarang_Field.setBorder(null);
        jPanel2.add(NamaBarang_Field);
        NamaBarang_Field.setBounds(340, 250, 650, 50);

        Kategori_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pcs", "pack", "gram", "lusin", "rim", "pasang", " ", " " }));
        Kategori_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kategori_ComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(Kategori_ComboBox);
        Kategori_ComboBox.setBounds(340, 350, 660, 60);

        SatuanBarang_Field.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        SatuanBarang_Field.setBorder(null);
        jPanel2.add(SatuanBarang_Field);
        SatuanBarang_Field.setBounds(340, 460, 660, 50);

        TambahBarang_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahBarang_LabelMouseClicked(evt);
            }
        });
        jPanel2.add(TambahBarang_Label);
        TambahBarang_Label.setBounds(520, 550, 230, 70);
        jPanel2.add(Kembali_Label);
        Kembali_Label.setBounds(21, 590, 70, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/Form Mendata Barang.png"))); // NOI18N
        jPanel2.add(Background);
        Background.setBounds(0, 0, 1060, 650);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1059, 650);

        setSize(new java.awt.Dimension(1081, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Kategori_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kategori_ComboBoxActionPerformed
        PreparedStatement ps;
        ResultSet rs; 

    }//GEN-LAST:event_Kategori_ComboBoxActionPerformed

    private void TambahBarang_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahBarang_LabelMouseClicked
        // variabel untuk mengekseksusi query
        PreparedStatement ps;
        // sebuah cursor untuk baris dari tabel tersebut
        ResultSet rs;

        String Nama_Barang = NamaBarang_Field.getText();

        // Query memasukkan nama_barang
        if (cekTextField()) {
            // melakukan pengecekan nama_barang ada atau tidak 
            if (!CekBarang(Nama_Barang)) {
                // menyimpan query yang digunakan pada SQL
                String queryMendataBarang = "INSERT INTO tb_barang(nama_barang) VALUES (?)";
                try {
                    // mencoba eksekusi query
                    ps = KoneksiDatabase.getConnection().prepareStatement(queryMendataBarang);
                    // pengganti Value harus sesuai order pada tabel yang digunakan untuk query
                    ps.setString(1, Nama_Barang);
                    // Setelah menjalankan query INSERT terhadap barang
                    try {
                        if (ps.executeUpdate() != 0) {
                            JOptionPane.showMessageDialog(null, "Barang Terdaftarkan Pada Sistem ! ");
                        } else {
                            JOptionPane.showMessageDialog(null, "Error, Barang Tidak Terdaftar, Silahkan Cek Data");
                        }
                        // jika tidak akan mendapatkan error dari dialog dan exeception handler
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                    // jika query tidak terjalankan akan diberikan SQLExeption pada terminal
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        }
    }//GEN-LAST:event_TambahBarang_LabelMouseClicked

    /** Method untuk mengecek ketersediaan Nama Barang 
     *  yang digunakan dengan melakukan query terhadap database 
     *  nantinya pengecekan ini akan dikembalikan terhadap method klik
     *
     *  2005551091 - Gede Rico Wijaya*/
     public boolean CekBarang(String Nama_Barang) {
        PreparedStatement st;
        ResultSet rs;

        boolean Nama_Barang_terdaftar = false;

        // query yang akan dijalankan pada database
        String query = "SELECT * FROM tb_barang WHERE nama_barang = ?";

        // pengecekan Nama_Barang
        try {
            st = KoneksiDatabase.getConnection().prepareStatement(query);
            st.setString(1, Nama_Barang);
            rs = st.executeQuery();

            if (rs.next()) {
                Nama_Barang_terdaftar = true;
                JOptionPane.showMessageDialog(null, "Nama_Barang Sudah Terdaftar, Silahkan Pilih Username lain !",
                        "Gagal terdaftar", 2);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        return Nama_Barang_terdaftar;
    }


    /** Method untuk mengecek kekosongan text Field */
    public boolean cekTextField() {
        String NamaBarang  = NamaBarang_Field.getText();

        // mengecek field yang kosong
        if (NamaBarang.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Salah satu kotak tidak diisi data", "kotak Kosong", 2);
            return false;
        // jika field tidak kosong
        } else {
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMendataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JComboBox<String> Kategori_ComboBox;
    private javax.swing.JLabel Kembali_Label;
    private javax.swing.JTextField NamaBarang_Field;
    private javax.swing.JTextField SatuanBarang_Field;
    private javax.swing.JLabel TambahBarang_Label;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
