/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

/**
 *
 * @author ASUS
 */
public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormHome
     */
    public FormHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PencatatanStok_Label = new javax.swing.JLabel();
        Keluar_Label = new javax.swing.JLabel();
        MendataBarang_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 40, 45, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        PencatatanStok_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PencatatanStok_LabelMouseClicked(evt);
            }
        });
        getContentPane().add(PencatatanStok_Label);
        PencatatanStok_Label.setBounds(690, 590, 60, 60);

        Keluar_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Keluar_LabelMouseClicked(evt);
            }
        });
        getContentPane().add(Keluar_Label);
        Keluar_Label.setBounds(890, 590, 60, 50);

        MendataBarang_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MendataBarang_LabelMouseClicked(evt);
            }
        });
        getContentPane().add(MendataBarang_Label);
        MendataBarang_Label.setBounds(490, 460, 140, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/Beranda.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 1080, 710);

        setSize(new java.awt.Dimension(1070, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Keluar_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keluar_LabelMouseClicked
        FormKeluar keluar = new FormKeluar();
        keluar.show();
        this.dispose();
    }//GEN-LAST:event_Keluar_LabelMouseClicked

    private void PencatatanStok_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PencatatanStok_LabelMouseClicked
        
    }//GEN-LAST:event_PencatatanStok_LabelMouseClicked

    private void MendataBarang_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MendataBarang_LabelMouseClicked
        FormMendataBarang data = new FormMendataBarang();
        data.show();
        this.dispose();
    }//GEN-LAST:event_MendataBarang_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Keluar_Label;
    private javax.swing.JLabel MendataBarang_Label;
    private javax.swing.JLabel PencatatanStok_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
