/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

/**
 *
 * @author ASUS
 */
public class FormLupaPassword extends javax.swing.JFrame {

    /**
     * Creates new form FormLupaPassword
     */
    public FormLupaPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pulihkan_Label = new javax.swing.JLabel();
        Email_Field = new javax.swing.JTextField();
        KataSandi_Field = new javax.swing.JPasswordField();
        KonfirmasiKataSandi_Field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(Pulihkan_Label);
        Pulihkan_Label.setBounds(500, 620, 170, 60);

        Email_Field.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        Email_Field.setBorder(null);
        jPanel1.add(Email_Field);
        Email_Field.setBounds(410, 420, 440, 40);

        KataSandi_Field.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        KataSandi_Field.setBorder(null);
        jPanel1.add(KataSandi_Field);
        KataSandi_Field.setBounds(410, 490, 440, 40);

        KonfirmasiKataSandi_Field.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        KonfirmasiKataSandi_Field.setBorder(null);
        jPanel1.add(KonfirmasiKataSandi_Field);
        KonfirmasiKataSandi_Field.setBounds(410, 550, 440, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/Lupa Password.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 690);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 700);

        setSize(new java.awt.Dimension(1113, 743));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLupaPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email_Field;
    private javax.swing.JPasswordField KataSandi_Field;
    private javax.swing.JPasswordField KonfirmasiKataSandi_Field;
    private javax.swing.JLabel Pulihkan_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
