/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

/**
 *
 * @author ASUS
 */
public class FormMendataBarang extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public FormMendataBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputNamaBarang = new javax.swing.JTextField();
        TambahBarang = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        InputKategori = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        InputNamaBarang.setBorder(null);
        InputNamaBarang.setCaretColor(new java.awt.Color(255, 255, 255));
        InputNamaBarang.setOpaque(false);
        InputNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNamaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(InputNamaBarang);
        InputNamaBarang.setBounds(340, 240, 660, 70);

        TambahBarang.setBackground(new java.awt.Color(255, 255, 255));
        TambahBarang.setForeground(new java.awt.Color(255, 255, 255));
        TambahBarang.setBorder(null);
        TambahBarang.setOpaque(false);
        TambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahBarangActionPerformed(evt);
            }
        });
        getContentPane().add(TambahBarang);
        TambahBarang.setBounds(520, 540, 230, 80);

        Kembali.setBorder(null);
        getContentPane().add(Kembali);
        Kembali.setBounds(23, 580, 70, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 440, 660, 70);
        getContentPane().add(InputKategori);
        InputKategori.setBounds(340, 340, 660, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/Form Mendata Barang.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1080, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void InputNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNamaBarangActionPerformed

    private void TambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMendataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMendataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputKategori;
    private javax.swing.JTextField InputNamaBarang;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton TambahBarang;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
