/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user_interface;

/**
 *
 * @author ASUS
 */
public class MenuLogin extends javax.swing.JFrame {

    /** Creates new form MenuLogin */
    public MenuLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowPassword = new javax.swing.JButton();
        NamaPengguna = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        LupaKataSandi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Masuk = new javax.swing.JButton();
        Daftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1098, 698));
        getContentPane().setLayout(null);

        ShowPassword.setBackground(new java.awt.Color(214, 236, 243));
        ShowPassword.setForeground(new java.awt.Color(214, 236, 243));
        ShowPassword.setBorder(null);
        ShowPassword.setOpaque(false);
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPassword);
        ShowPassword.setBounds(980, 400, 50, 30);

        NamaPengguna.setBorder(null);
        NamaPengguna.setCaretColor(new java.awt.Color(255, 255, 255));
        NamaPengguna.setOpaque(false);
        getContentPane().add(NamaPengguna);
        NamaPengguna.setBounds(590, 330, 380, 30);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(590, 410, 380, 26);
        getContentPane().add(LupaKataSandi);
        LupaKataSandi.setBounds(810, 450, 180, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/Login.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 1120, 710);

        Masuk.setText("jButton1");
        getContentPane().add(Masuk);
        Masuk.setBounds(720, 510, 170, 60);

        Daftar.setText("jButton1");
        getContentPane().add(Daftar);
        Daftar.setBounds(720, 630, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Daftar;
    private javax.swing.JButton LupaKataSandi;
    private javax.swing.JButton Masuk;
    private javax.swing.JTextField NamaPengguna;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton ShowPassword;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
