/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author Monica 
 */
public class FormDaftar extends javax.swing.JFrame {
    ResultSet rs;
    String sql;
    Statement stat;
    /**
     * Creates new form FormDaftar
     */
    public FormDaftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        KataSandi_Field = new javax.swing.JPasswordField();
        KonfirmasiKataSandi_Field = new javax.swing.JPasswordField();
        Email_TextField = new javax.swing.JTextField();
        NamaPengguna_TextField = new javax.swing.JTextField();
        Masuk_Label = new javax.swing.JLabel();
        Daftar_Label = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(214, 236, 243));
        jPanel2.setLayout(null);

        KataSandi_Field.setBackground(new java.awt.Color(214, 236, 243));
        KataSandi_Field.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        KataSandi_Field.setForeground(new java.awt.Color(214, 236, 243));
        KataSandi_Field.setBorder(null);
        KataSandi_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KataSandi_FieldActionPerformed(evt);
            }
        });
        jPanel2.add(KataSandi_Field);
        KataSandi_Field.setBounds(720, 350, 320, 20);

        KonfirmasiKataSandi_Field.setBackground(new java.awt.Color(214, 236, 243));
        KonfirmasiKataSandi_Field.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        KonfirmasiKataSandi_Field.setForeground(new java.awt.Color(214, 236, 243));
        KonfirmasiKataSandi_Field.setBorder(null);
        jPanel2.add(KonfirmasiKataSandi_Field);
        KonfirmasiKataSandi_Field.setBounds(720, 410, 320, 20);

        Email_TextField.setBackground(new java.awt.Color(214, 236, 243));
        Email_TextField.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        Email_TextField.setBorder(null);
        Email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_TextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(Email_TextField);
        Email_TextField.setBounds(720, 210, 330, 30);

        NamaPengguna_TextField.setBackground(new java.awt.Color(214, 236, 243));
        NamaPengguna_TextField.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        NamaPengguna_TextField.setBorder(null);
        NamaPengguna_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPengguna_TextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(NamaPengguna_TextField);
        NamaPengguna_TextField.setBounds(720, 280, 330, 26);

        Masuk_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Masuk_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Masuk_LabelMouseEntered(evt);
            }
        });
        jPanel2.add(Masuk_Label);
        Masuk_Label.setBounds(920, 580, 70, 20);

        Daftar_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Daftar_LabelMouseClicked(evt);
            }
        });
        jPanel2.add(Daftar_Label);
        Daftar_Label.setBounds(730, 490, 220, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/Daftar.png"))); // NOI18N
        jPanel2.add(Background);
        Background.setBounds(0, 5, 1098, 695);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 700);

        setSize(new java.awt.Dimension(1119, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_TextFieldActionPerformed

    private void NamaPengguna_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPengguna_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPengguna_TextFieldActionPerformed

    private void KataSandi_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KataSandi_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KataSandi_FieldActionPerformed

    private void Daftar_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_LabelMouseClicked

    }//GEN-LAST:event_Daftar_LabelMouseClicked

    private void Masuk_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Masuk_LabelMouseEntered
        
    }//GEN-LAST:event_Masuk_LabelMouseEntered

    private void Masuk_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Masuk_LabelMouseClicked
        FormLogin login = new FormLogin();
        login.show();
        this.dispose();
    }//GEN-LAST:event_Masuk_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Daftar_Label;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JPasswordField KataSandi_Field;
    private javax.swing.JPasswordField KonfirmasiKataSandi_Field;
    private javax.swing.JLabel Masuk_Label;
    private javax.swing.JTextField NamaPengguna_TextField;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
